# Generated by Django 3.2.10 on 2025-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон покупателя'),
        ),
    ]
